# note: each of these fields are OPTIONAL
[dev]
  command = "pnpm start" # Command to start your dev server
  targetPort = 3000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "./dist" # The path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser